version: "3.9"
services:
 flask_order_service_app:
   container_name: order_service_app
   image: order_service/flask_api:1.0
   build: .
   ports:
     - "3000:3000"
   environment:
     - DB_URL=${DB_URL}

   depends_on:
   - flask_order_db

 flask_order_db:
   container_name: flask_order_db
   image: postgres:12
   ports:
     - "5430:5432"
   environment:
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_DB=${POSTGRES_DB}
   volumes:
     - pgdata:/var/lib/postgresql/data

volumes:
 pgdata: {}